// Writes src/index.ts with a named alias for every schema, so app code can
// import `Device` instead of `components["schemas"]["Device"]`.
import fs from 'node:fs';
const doc = JSON.parse(fs.readFileSync(new URL('../openapi.json', import.meta.url), 'utf8'));
const names = Object.keys(doc.components.schemas).sort();
const lines = [
  '// Generated by scripts/aliases.mjs. Do not edit.',
  'import type { components, paths } from "./api";',
  '',
  'export type { components, paths };',
  '',
  ...names.map((n) => `export type ${n} = components["schemas"]["${n}"];`),
  '',
];
fs.writeFileSync(new URL('../src/index.ts', import.meta.url), lines.join('\n'));
console.log(`aliases: ${names.length} schemas`);
