-- +goose Up
-- simhook core schema.
-- Conventions: uuid primary keys (v7 generated by the app, gen_random_uuid() as
-- a fallback), timestamptz everywhere, soft deletes only where history must
-- survive (devices, webhooks). Secrets are never stored in the clear: API keys,
-- device tokens, session tokens and one-time codes are SHA-256 hashed; webhook
-- signing secrets are AES-GCM encrypted with the server key.

create extension if not exists citext;

-- ---------------------------------------------------------------------------
-- Accounts
-- ---------------------------------------------------------------------------

create table users (
    id                      uuid primary key default gen_random_uuid(),
    email                   citext not null unique,
    name                    text,
    password_hash           text,                      -- null for OAuth-only accounts
    google_sub              text unique,
    avatar_url              text,
    role                    text not null default 'user' check (role in ('user', 'admin')),
    email_verified_at       timestamptz,
    banned_at               timestamptz,
    deletion_requested_at   timestamptz,
    deletion_reason         text,
    onboarding              jsonb not null default '{}'::jsonb,
    last_login_at           timestamptz,
    created_at              timestamptz not null default now(),
    updated_at              timestamptz not null default now()
);

-- One-time codes: email verification and password reset.
create table user_tokens (
    id            uuid primary key default gen_random_uuid(),
    user_id       uuid not null references users (id) on delete cascade,
    kind          text not null check (kind in ('email_verify', 'password_reset')),
    token_hash    bytea not null unique,
    expires_at    timestamptz not null,
    consumed_at   timestamptz,
    created_at    timestamptz not null default now()
);
create index user_tokens_user_kind_idx on user_tokens (user_id, kind);

-- Dashboard sessions. The browser holds an httpOnly cookie; we hold the hash.
create table sessions (
    id            uuid primary key default gen_random_uuid(),
    user_id       uuid not null references users (id) on delete cascade,
    token_hash    bytea not null unique,
    user_agent    text,
    ip            text,
    expires_at    timestamptz not null,
    last_seen_at  timestamptz not null default now(),
    created_at    timestamptz not null default now()
);
create index sessions_user_idx on sessions (user_id);

-- Developer credentials. Scoped, optionally expiring, revocable.
create table api_keys (
    id            uuid primary key default gen_random_uuid(),
    user_id       uuid not null references users (id) on delete cascade,
    name          text not null default 'API key',
    prefix        text not null,                       -- display only, e.g. sh_live_a1b2c3d4
    key_hash      bytea not null unique,
    scopes        text[] not null default '{send,read,devices,webhooks}',
    expires_at    timestamptz,
    last_used_at  timestamptz,
    use_count     bigint not null default 0,
    revoked_at    timestamptz,
    created_at    timestamptz not null default now()
);
create index api_keys_user_active_idx on api_keys (user_id) where revoked_at is null;

-- ---------------------------------------------------------------------------
-- Devices
-- ---------------------------------------------------------------------------

create table devices (
    id                          uuid primary key default gen_random_uuid(),
    user_id                     uuid not null references users (id) on delete cascade,
    name                        text not null,
    enabled                     boolean not null default true,
    is_default                  boolean not null default false,

    -- Stable hardware identity computed on the phone, so the same handset
    -- re-pairs to the same row instead of creating a duplicate.
    hardware_key                text not null,
    manufacturer                text,
    brand                       text,
    model                       text,
    build_id                    text,
    os_version                  text,
    os_api_level                int,
    app_version_name            text,
    app_version_code            int,

    -- Push channel. Provider-agnostic column names; FCM today.
    push_token                  text,
    push_token_updated_at       timestamptz,
    push_token_invalidated_at   timestamptz,
    push_token_invalid_reason   text,

    -- Settings. The server is the source of truth; the phone syncs on heartbeat.
    receive_enabled             boolean not null default false,
    send_delay_seconds          int not null default 5
                                    check (send_delay_seconds between 0 and 3600),
    heartbeat_interval_minutes  int not null default 30
                                    check (heartbeat_interval_minutes between 15 and 1440),
    preferred_sim_subscription_id int,

    -- Latest telemetry only. History is not a v1 feature.
    last_heartbeat_at           timestamptz,
    online                      boolean not null default false,
    telemetry                   jsonb not null default '{}'::jsonb,
    sims                        jsonb not null default '[]'::jsonb,
    sent_count                  bigint not null default 0,
    received_count              bigint not null default 0,

    deleted_at                  timestamptz,
    created_at                  timestamptz not null default now(),
    updated_at                  timestamptz not null default now(),

    unique (user_id, hardware_key)
);
create index devices_user_live_idx on devices (user_id) where deleted_at is null;
create unique index devices_one_default_per_user
    on devices (user_id) where is_default and deleted_at is null;
create index devices_heartbeat_probe_idx
    on devices (last_heartbeat_at)
    where deleted_at is null and enabled and push_token is not null and push_token_invalidated_at is null;

-- Phone credentials. Scoped to device endpoints only; never a user API key.
create table device_tokens (
    id            uuid primary key default gen_random_uuid(),
    device_id     uuid not null references devices (id) on delete cascade,
    token_hash    bytea not null unique,
    last_used_at  timestamptz,
    revoked_at    timestamptz,
    created_at    timestamptz not null default now()
);
create index device_tokens_device_active_idx on device_tokens (device_id) where revoked_at is null;

-- Short-lived pairing codes shown as a QR in the dashboard. The phone
-- exchanges one for a device row plus a device token.
create table pairing_codes (
    id                      uuid primary key default gen_random_uuid(),
    user_id                 uuid not null references users (id) on delete cascade,
    code_hash               bytea not null unique,
    expires_at              timestamptz not null,
    consumed_at             timestamptz,
    consumed_by_device_id   uuid references devices (id) on delete set null,
    created_at              timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Messages
-- ---------------------------------------------------------------------------

create type batch_status as enum ('queued', 'processing', 'completed', 'partial', 'failed', 'unknown');

-- One API send call. Counters are bumped atomically by status transitions,
-- never recomputed by scanning messages.
create table batches (
    id                        uuid primary key default gen_random_uuid(),
    user_id                   uuid not null references users (id) on delete cascade,
    device_id                 uuid not null references devices (id),
    api_key_id                uuid references api_keys (id) on delete set null,
    body                      text not null,
    recipient_count           int not null check (recipient_count > 0),
    recipient_preview         text not null,
    dispatched_count          int not null default 0,
    sent_count                int not null default 0,
    delivered_count           int not null default 0,
    failed_count              int not null default 0,
    unknown_count             int not null default 0,
    status                    batch_status not null default 'queued',
    scheduled_at              timestamptz,
    estimated_completion_at   timestamptz,
    completed_at              timestamptz,
    error                     text,
    created_at                timestamptz not null default now(),
    updated_at                timestamptz not null default now()
);
create index batches_user_created_idx on batches (user_id, created_at desc);

create type message_direction as enum ('outbound', 'inbound');
create type message_status as enum ('queued', 'dispatched', 'sent', 'delivered', 'failed', 'unknown', 'received');

create table messages (
    id                    uuid primary key default gen_random_uuid(),
    user_id               uuid not null references users (id) on delete cascade,
    device_id             uuid not null references devices (id),
    batch_id              uuid references batches (id) on delete set null,
    direction             message_direction not null,
    status                message_status not null,
    body                  text not null,

    -- outbound
    recipient             text,
    sim_subscription_id   int,
    dispatch_due_at       timestamptz,
    dispatched_at         timestamptz,
    sent_at               timestamptz,
    delivered_at          timestamptz,
    failed_at             timestamptz,
    error_code            text,
    error_message         text,

    -- inbound
    sender                text,
    received_at           timestamptz,
    fingerprint           text,                        -- computed on the phone

    created_at            timestamptz not null default now(),
    updated_at            timestamptz not null default now(),

    check (
        (direction = 'outbound' and recipient is not null)
     or (direction = 'inbound' and sender is not null and received_at is not null)
    )
);
-- Account history, keyset pagination on (created_at, id).
create index messages_user_history_idx on messages (user_id, created_at desc, id desc);
create index messages_device_dir_idx on messages (device_id, direction, created_at desc);
create index messages_batch_idx on messages (batch_id) where batch_id is not null;
-- Inbound idempotency: the phone's fingerprint is the key.
create unique index messages_inbound_fingerprint_idx
    on messages (device_id, fingerprint) where fingerprint is not null;
-- Reconciliation scan for stale in-flight messages.
create index messages_inflight_idx
    on messages (status, dispatch_due_at, dispatched_at)
    where status in ('queued', 'dispatched');

-- ---------------------------------------------------------------------------
-- Webhooks
-- ---------------------------------------------------------------------------

create type webhook_event as enum (
    'message.received',
    'message.sent',
    'message.delivered',
    'message.failed',
    'message.unknown',
    'device.online',
    'device.offline',
    'ping'
);

create table webhooks (
    id                uuid primary key default gen_random_uuid(),
    user_id           uuid not null references users (id) on delete cascade,
    name              text,
    url               text not null,
    secret_enc        bytea not null,                   -- AES-GCM, server key
    events            text[] not null check (
                          cardinality(events) > 0
                          and events <@ enum_range(null::webhook_event)::text[]
                      ),
    enabled           boolean not null default true,
    success_count     bigint not null default 0,
    failure_count     bigint not null default 0,
    last_attempt_at   timestamptz,
    last_success_at   timestamptz,
    last_failure_at   timestamptz,
    last_enabled_at   timestamptz,
    disabled_reason   text,
    deleted_at        timestamptz,
    created_at        timestamptz not null default now(),
    updated_at        timestamptz not null default now()
);
create index webhooks_user_live_idx on webhooks (user_id) where deleted_at is null;

create type delivery_status as enum ('pending', 'delivered', 'retrying', 'failed');

create table webhook_deliveries (
    id                uuid primary key default gen_random_uuid(),
    webhook_id        uuid not null references webhooks (id) on delete cascade,
    message_id        uuid references messages (id) on delete set null,
    device_id         uuid references devices (id) on delete set null,
    event             webhook_event not null,
    payload           jsonb not null,
    url               text not null,                    -- snapshot at enqueue time
    status            delivery_status not null default 'pending',
    attempt_count     int not null default 0,
    next_attempt_at   timestamptz,
    last_attempt_at   timestamptz,
    delivered_at      timestamptz,
    abandoned_at      timestamptz,
    http_status       int,
    response_excerpt  text,
    error             text,
    created_at        timestamptz not null default now()
);
create index webhook_deliveries_webhook_idx on webhook_deliveries (webhook_id, created_at desc);
create index webhook_deliveries_due_idx
    on webhook_deliveries (next_attempt_at) where status in ('pending', 'retrying');

-- ---------------------------------------------------------------------------
-- Plans, subscriptions, usage
-- ---------------------------------------------------------------------------

create table plans (
    id                    text primary key,             -- 'free', 'pro', 'scale', 'custom'
    name                  text not null,
    daily_limit           int not null,                 -- -1 unlimited
    monthly_limit         int not null,
    batch_limit           int not null,
    device_limit          int not null,
    monthly_price_cents   int not null default 0,
    yearly_price_cents    int not null default 0,
    active                boolean not null default true,
    sort_order            int not null default 0
);

create table subscriptions (
    id                          uuid primary key default gen_random_uuid(),
    user_id                     uuid not null references users (id) on delete cascade,
    plan_id                     text not null references plans (id),
    status                      text not null default 'active',
    provider                    text,                   -- 'polar', 'stripe', null for free or manual
    provider_subscription_id    text,
    provider_customer_id        text,
    billing_interval            text,                   -- 'month', 'year'
    current_period_start        timestamptz,
    current_period_end          timestamptz,
    cancel_at_period_end        boolean not null default false,
    ended_at                    timestamptz,
    limit_overrides             jsonb not null default '{}'::jsonb,
    created_at                  timestamptz not null default now(),
    updated_at                  timestamptz not null default now()
);
create unique index subscriptions_one_live_per_user on subscriptions (user_id) where ended_at is null;

-- Cheap limit checks: one upsert per send, no counting rows.
create table usage_counters (
    user_id       uuid not null references users (id) on delete cascade,
    period_kind   text not null check (period_kind in ('day', 'month')),
    period_start  date not null,
    sent          int not null default 0,
    received      int not null default 0,
    primary key (user_id, period_kind, period_start)
);

-- Placeholder tiers so limit checks work in development. Real pricing is a
-- product decision and is set in a later migration before launch.
insert into plans (id, name, daily_limit, monthly_limit, batch_limit, device_limit, monthly_price_cents, yearly_price_cents, sort_order) values
    ('free',  'Free',  30,   500,   25,   1,  0,    0,     0),
    ('pro',   'Pro',   -1,   10000, 500,  3,  1200, 12000, 1),
    ('scale', 'Scale', -1,   50000, 2500, 10, 3900, 39000, 2);

-- ---------------------------------------------------------------------------
-- updated_at maintenance
-- ---------------------------------------------------------------------------

-- +goose StatementBegin
create or replace function set_updated_at() returns trigger language plpgsql as $$
begin
    new.updated_at := now();
    return new;
end
$$;
-- +goose StatementEnd

create trigger users_updated_at         before update on users         for each row execute function set_updated_at();
create trigger devices_updated_at       before update on devices       for each row execute function set_updated_at();
create trigger batches_updated_at       before update on batches       for each row execute function set_updated_at();
create trigger messages_updated_at      before update on messages      for each row execute function set_updated_at();
create trigger webhooks_updated_at      before update on webhooks      for each row execute function set_updated_at();
create trigger subscriptions_updated_at before update on subscriptions for each row execute function set_updated_at();

-- +goose Down
drop trigger if exists subscriptions_updated_at on subscriptions;
drop trigger if exists webhooks_updated_at on webhooks;
drop trigger if exists messages_updated_at on messages;
drop trigger if exists batches_updated_at on batches;
drop trigger if exists devices_updated_at on devices;
drop trigger if exists users_updated_at on users;
drop function if exists set_updated_at();
drop table if exists usage_counters;
drop table if exists subscriptions;
drop table if exists plans;
drop table if exists webhook_deliveries;
drop type if exists delivery_status;
drop table if exists webhooks;
drop type if exists webhook_event;
drop table if exists messages;
drop type if exists message_status;
drop type if exists message_direction;
drop table if exists batches;
drop type if exists batch_status;
drop table if exists pairing_codes;
drop table if exists device_tokens;
drop table if exists devices;
drop table if exists api_keys;
drop table if exists sessions;
drop table if exists user_tokens;
drop table if exists users;
