/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List API keys */
        get: operations["list-api-keys"];
        put?: never;
        /**
         * Create an API key
         * @description The full key is returned once. Only its hash is stored.
         */
        post: operations["create-api-key"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/api-keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an API key */
        delete: operations["delete-api-key"];
        options?: never;
        head?: never;
        /** Rename an API key */
        patch: operations["rename-api-key"];
        trace?: never;
    };
    "/v1/api-keys/{id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke an API key
         * @description Stops the key working immediately while keeping its record.
         */
        post: operations["revoke-api-key"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in
         * @description Checks the password and sets the session cookie used by the dashboard.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current account
         * @description The account behind the credentials, with its plan limits and usage this period.
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change password */
        post: operations["change-password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set a new password with a reset code
         * @description Completes a reset. Every existing session is signed out.
         */
        post: operations["reset-password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a password reset code
         * @description Emails a code if the address has an account. The response is the same either way.
         */
        post: operations["request-password-reset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update profile */
        patch: operations["update-profile"];
        trace?: never;
    };
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account
         * @description Creates the account, signs it in with a session cookie, and emails a verification code. Sending is blocked until the email is verified.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify the email address */
        post: operations["verify-email"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/verify-email/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend the verification code */
        post: operations["send-verification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List sends
         * @description Every send on the account, newest first, with per-status counts.
         */
        get: operations["list-batches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/batches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a send
         * @description The batch plus one message per recipient. Poll this to follow a send.
         */
        get: operations["get-batch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/device": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** This phone's record */
        get: operations["device-self"];
        put?: never;
        post?: never;
        /**
         * Unpair this phone
         * @description Removes this phone from the account and revokes its token. Message history is kept.
         */
        delete: operations["device-unpair"];
        options?: never;
        head?: never;
        /** Change this phone's settings */
        patch: operations["device-update-self"];
        trace?: never;
    };
    "/v1/device/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check in
         * @description Reports the phone is alive and uploads its state. The response carries the settings the phone should apply.
         */
        post: operations["device-heartbeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/device/inbound": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report a received SMS
         * @description Stores an incoming message and fans out message.received. Returns 201 when stored, 200 when it was already known.
         */
        post: operations["device-report-inbound"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/device/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** This phone's messages */
        get: operations["device-messages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/device/messages/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report a send outcome
         * @description Idempotent. Out-of-order reports never move a message backwards.
         */
        post: operations["device-report-status"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/device/outbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Messages to send
         * @description The messages this phone should send now, oldest first. Fetching marks them dispatched. A message stays in the list until the phone reports its outcome, so a phone that lost one gets it again.
         */
        get: operations["device-outbox"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/device/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pair a phone
         * @description Exchanges a pairing code for a device record and a device token. Called by the phone app.
         */
        post: operations["pair-device"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/device/push-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new push token */
        post: operations["device-push-token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List devices
         * @description Every phone paired with the account, default first.
         */
        get: operations["list-devices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a device */
        get: operations["get-device"];
        put?: never;
        post?: never;
        /**
         * Unpair a device
         * @description Revokes the phone's token and stops sends to it. Message history is kept.
         */
        delete: operations["unpair-device"];
        options?: never;
        head?: never;
        /**
         * Update device settings
         * @description Only the fields you send change. The phone is told at once and reloads its settings within seconds; a phone that is offline picks them up when it is back.
         */
        patch: operations["update-device"];
        trace?: never;
    };
    "/v1/devices/{id}/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Make this the default device
         * @description Sends that omit device_id go out from the default device.
         */
        post: operations["set-default-device"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/pairing-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a pairing code
         * @description Mints a code valid for 10 minutes. Enter it in the phone app, or show pair_url as a QR code for the app to scan.
         */
        post: operations["create-pairing-code"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/pairing-codes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check a pairing code
         * @description Whether a phone has used the code yet, and which one. Poll it while showing the code.
         */
        get: operations["get-pairing-code"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List messages
         * @description Sent and received messages across the account, newest first, with delivery state on each. To poll for new messages, request order=asc with a from bound and follow next_cursor.
         */
        get: operations["list-messages"];
        put?: never;
        /**
         * Send an SMS
         * @description Queues one text to one or more recipients from a phone on the account. Acceptance is not delivery: follow the batch or subscribe to webhooks for the outcome. Every recipient counts as one message against the plan.
         */
        post: operations["send-message"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/messages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a message */
        get: operations["get-message"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List plans
         * @description The public plan catalogue with limits and prices. No credentials needed.
         */
        get: operations["list-plans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Account totals */
        get: operations["get-stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List webhooks */
        get: operations["list-webhooks"];
        put?: never;
        /**
         * Create a webhook
         * @description Subscribes an https URL to events. Each delivery is a JSON POST signed with the returned secret: X-Simhook-Signature is t=<unix>,v1=<hex hmac-sha256 of "<t>.<body>">. Respond 2xx within 30 seconds; other responses are retried for about two days.
         */
        post: operations["create-webhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a webhook */
        get: operations["get-webhook"];
        put?: never;
        post?: never;
        /** Delete a webhook */
        delete: operations["delete-webhook"];
        options?: never;
        head?: never;
        /** Update a webhook */
        patch: operations["update-webhook"];
        trace?: never;
    };
    "/v1/webhooks/{id}/rotate-secret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the signing secret
         * @description Deliveries queued from now on are signed with the new secret.
         */
        post: operations["rotate-webhook-secret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a test event
         * @description Queues a ping delivery so you can check your endpoint and signature verification.
         */
        post: operations["test-webhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List deliveries
         * @description Delivery attempts across every webhook on the account, newest first, including webhooks since deleted.
         */
        get: operations["list-deliveries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/deliveries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a delivery */
        get: operations["get-delivery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        APIError: {
            /** @description Stable machine-readable code. */
            code: string;
            /** @description Per-field problems, when applicable. */
            errors?: components["schemas"]["FieldError"][];
            /** @description Human-readable explanation. */
            message: string;
            /**
             * Format: int64
             * @description HTTP status code.
             */
            status: number;
        };
        APIKey: {
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            expires_at: string | null;
            id: string;
            /** Format: date-time */
            last_used_at: string | null;
            name: string;
            prefix: string;
            /** Format: date-time */
            revoked_at: string | null;
            scopes: string[];
            /** Format: int64 */
            use_count: number;
        };
        Batch: {
            body: string;
            /** Format: date-time */
            completed_at: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: int32 */
            delivered_count: number;
            device_id: string;
            /** Format: int32 */
            dispatched_count: number;
            error: string | null;
            /** Format: date-time */
            estimated_completion_at: string | null;
            /** Format: int32 */
            failed_count: number;
            id: string;
            /** Format: int32 */
            recipient_count: number;
            recipient_preview: string;
            /** Format: date-time */
            scheduled_at: string | null;
            /** Format: int32 */
            sent_count: number;
            status: string;
            /** Format: int32 */
            unknown_count: number;
            /** Format: date-time */
            updated_at: string;
        };
        BatchesOutputBody: {
            data: components["schemas"]["Batch"][];
            next_cursor?: string;
        };
        BatchOutputBody: {
            batch: components["schemas"]["Batch"];
            messages: components["schemas"]["Message"][];
        };
        ChangePasswordInputBody: {
            current_password: string;
            new_password: string;
        };
        CreateKeyInputBody: {
            /**
             * Format: date-time
             * @description Optional expiry.
             */
            expires_at?: string;
            /** @description Label shown in the dashboard. */
            name?: string;
            /** @description Any of send, read, devices, webhooks. Defaults to all. */
            scopes?: string[];
        };
        CreateKeyOutputBody: {
            api_key: components["schemas"]["APIKey"];
            /** @description The full key. It is shown once and never stored. */
            key: string;
        };
        CreateWebhookInputBody: {
            /** @description Any of message.received, message.sent, message.delivered, message.failed, message.unknown, device.online, device.offline, ping. */
            events: string[];
            name?: string;
            /**
             * Format: uri
             * @description HTTPS endpoint that receives POSTs.
             */
            url: string;
        };
        DeliveriesOutputBody: {
            data: components["schemas"]["Delivery"][];
            next_cursor?: string;
        };
        Delivery: {
            /** Format: date-time */
            abandoned_at: string | null;
            /** Format: int32 */
            attempt_count: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            delivered_at: string | null;
            device_id: string;
            error: string | null;
            event: string;
            /** Format: int32 */
            http_status: number | null;
            id: string;
            /** Format: date-time */
            last_attempt_at: string | null;
            message_id: string;
            /** Format: date-time */
            next_attempt_at: string | null;
            payload: unknown;
            response_excerpt: string | null;
            status: string;
            url: string;
            webhook_id: string;
        };
        DeliveryOutputBody: {
            delivery: components["schemas"]["Delivery"];
        };
        Device: {
            /** Format: int32 */
            app_version_code: number | null;
            app_version_name: string | null;
            brand: string | null;
            /** Format: date-time */
            created_at: string;
            enabled: boolean;
            /** Format: int32 */
            heartbeat_interval_minutes: number;
            id: string;
            is_default: boolean;
            /** Format: date-time */
            last_heartbeat_at: string | null;
            manufacturer: string | null;
            model: string | null;
            name: string;
            online: boolean;
            /** Format: int32 */
            os_api_level: number | null;
            os_version: string | null;
            /** Format: int32 */
            preferred_sim_subscription_id: number | null;
            push_token_invalid_reason: string | null;
            /** Format: date-time */
            push_token_invalidated_at: string | null;
            receive_enabled: boolean;
            /** Format: int64 */
            received_count: number;
            /** Format: int32 */
            send_delay_seconds: number;
            /** Format: int64 */
            sent_count: number;
            sims: unknown;
            telemetry: unknown;
            /** Format: date-time */
            updated_at: string;
        };
        DeviceOutputBody: {
            device: components["schemas"]["Device"];
        };
        DevicePatchBody: {
            /** @description Set true to fall back to the phone's default SIM. */
            clear_preferred_sim?: boolean;
            /** @description A disabled phone receives no new sends, and sends already queued for it fail. */
            enabled?: boolean;
            /** Format: int32 */
            heartbeat_interval_minutes?: number;
            name?: string;
            /**
             * Format: int32
             * @description SIM to send from when a send names none.
             */
            preferred_sim_subscription_id?: number;
            /** @description Forward incoming SMS from this phone. */
            receive_enabled?: boolean;
            /**
             * Format: int32
             * @description Pause between consecutive sends on the phone.
             */
            send_delay_seconds?: number;
        };
        DevicePatchSelfBody: {
            /** @description Set true to fall back to the phone's default SIM. */
            clear_preferred_sim?: boolean;
            /** @description A disabled phone receives no new sends. */
            enabled?: boolean;
            name?: string;
            /**
             * Format: int32
             * @description SIM to send from when a send names none.
             */
            preferred_sim_subscription_id?: number;
            /** @description Forward incoming SMS from this phone. */
            receive_enabled?: boolean;
            /**
             * Format: int32
             * @description Pause between consecutive sends.
             */
            send_delay_seconds?: number;
        };
        DevicesOutputBody: {
            data: components["schemas"]["Device"][];
        };
        FieldError: {
            /** @description Location of the problem, for example body.to[0]. */
            field?: string;
            /** @description What is wrong with it. */
            message: string;
        };
        HeartbeatInputBody: {
            /** Format: int32 */
            app_version_code?: number;
            app_version_name?: string;
            /** Format: int32 */
            os_api_level?: number;
            os_version?: string;
            push_token?: string;
            /** @description Array of SIM descriptors with subscription_id, carrier, slot, country. */
            sims?: unknown;
            /** @description Battery, network, storage, uptime, timezone, locale. Free-form object. */
            telemetry?: unknown;
        };
        InboundInputBody: {
            /** @description The text, with concatenated parts already joined. */
            body: string;
            /** @description Hash of sender, body, and timestamp computed on the phone. Repeats are ignored. */
            fingerprint?: string;
            /** Format: date-time */
            received_at: string;
            sender: string;
            /** Format: int32 */
            sim_subscription_id?: number;
        };
        InboundOutputBody: {
            /** @description False when this message was already stored. */
            inserted: boolean;
            message: components["schemas"]["Message"];
        };
        Limits: {
            /** Format: int32 */
            batch_limit: number;
            /** Format: int32 */
            daily_limit: number;
            /** Format: int32 */
            device_limit: number;
            /** Format: int32 */
            monthly_limit: number;
            plan_id: string;
            plan_name: string;
        };
        ListKeysOutputBody: {
            data: components["schemas"]["APIKey"][];
        };
        LoginInputBody: {
            /** Format: email */
            email: string;
            password: string;
        };
        MeOutputBody: {
            limits: components["schemas"]["Limits"];
            usage: components["schemas"]["UsageView"];
            user: components["schemas"]["User"];
        };
        Message: {
            batch_id: string;
            body: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            delivered_at: string | null;
            device_id: string;
            direction: string;
            /** Format: date-time */
            dispatched_at: string | null;
            error_code: string | null;
            error_message: string | null;
            /** Format: date-time */
            failed_at: string | null;
            id: string;
            /** Format: date-time */
            received_at: string | null;
            recipient: string | null;
            sender: string | null;
            /** Format: date-time */
            sent_at: string | null;
            /** Format: int32 */
            sim_subscription_id: number | null;
            status: string;
            /** Format: date-time */
            updated_at: string;
        };
        MessageOutputBody: {
            message: components["schemas"]["Message"];
        };
        MessagesOutputBody: {
            data: components["schemas"]["Message"][];
            /** @description Pass as cursor to get the next page. Absent on the last page. */
            next_cursor?: string;
        };
        OutboxOutputBody: {
            data: components["schemas"]["OutboxRow"][];
        };
        OutboxRow: {
            batch_id: string;
            body: string;
            id: string;
            /** Format: int32 */
            sim_subscription_id: number | null;
            to: string;
        };
        PairingCodeOutputBody: {
            /** @description Type this into the app, or scan pair_url as a QR code. */
            code: string;
            /** Format: date-time */
            expires_at: string;
            /** @description Poll GET /v1/devices/pairing-codes/{id} to learn when a phone has used the code. */
            id: string;
            /** @description Deep link the app understands. Encode it as a QR code. */
            pair_url: string;
        };
        PairingStatusOutputBody: {
            /** @description True once a phone has paired with this code. */
            consumed: boolean;
            /** @description The phone that used the code, once one has. */
            device: components["schemas"]["Device"];
            /** Format: date-time */
            expires_at: string;
        };
        PairInputBody: {
            /** Format: int32 */
            app_version_code?: number;
            app_version_name?: string;
            brand?: string;
            build_id?: string;
            /** @description Pairing code from the dashboard. */
            code: string;
            /** @description Stable hash the app derives from the handset, so re-pairing finds the same device. */
            hardware_key: string;
            manufacturer?: string;
            model?: string;
            name?: string;
            /** Format: int32 */
            os_api_level?: number;
            os_version?: string;
            push_token?: string;
        };
        PairOutputBody: {
            device: components["schemas"]["Device"];
            /** @description Bearer token for /v1/device endpoints. Shown once. */
            device_token: string;
        };
        Plan: {
            active: boolean;
            /** Format: int32 */
            batch_limit: number;
            /** Format: int32 */
            daily_limit: number;
            /** Format: int32 */
            device_limit: number;
            id: string;
            /** Format: int32 */
            monthly_limit: number;
            /** Format: int32 */
            monthly_price_cents: number;
            name: string;
            /** Format: int32 */
            yearly_price_cents: number;
        };
        PlansOutputBody: {
            data: components["schemas"]["Plan"][];
        };
        ProfileInputBody: {
            name?: string;
        };
        PushTokenInputBody: {
            token: string;
        };
        RegisterInputBody: {
            /**
             * Format: email
             * @description Sign-in email. A verification code is sent to it.
             */
            email: string;
            /** @description Display name. */
            name?: string;
            /** @description At least 10 characters. */
            password: string;
        };
        RenameKeyInputBody: {
            name: string;
        };
        ResetInputBody: {
            code: string;
            /** Format: email */
            email: string;
            new_password: string;
        };
        ResetRequestInputBody: {
            /** Format: email */
            email: string;
        };
        SecretOutputBody: {
            secret: string;
        };
        SendInputBody: {
            /** @description Message text. Long texts are sent as concatenated SMS. */
            body: string;
            /** @description Phone to send from. Defaults to the account's default device, else the most recently online one. */
            device_id?: string;
            /**
             * Format: date-time
             * @description Send later, up to 7 days ahead.
             */
            scheduled_at?: string;
            /**
             * Format: int32
             * @description SIM to use on a multi-SIM phone. Unknown ids fall back to the phone's preferred SIM.
             */
            sim_subscription_id?: number;
            /** @description Recipient phone numbers, ideally E.164 such as +14155550123. */
            to: string[];
        };
        SendOutputBody: {
            batch: components["schemas"]["Batch"];
            /** @description One id per recipient, in the order given after de-duplication. */
            message_ids: string[];
        };
        SessionOutputBody: {
            user: components["schemas"]["User"];
        };
        Stats: {
            /** Format: int64 */
            devices: number;
            /** Format: int64 */
            received: number;
            /** Format: int64 */
            sent: number;
        };
        StatusReportInputBody: {
            /**
             * Format: date-time
             * @description When it happened on the phone. Defaults to now.
             */
            at?: string;
            error_code?: string;
            error_message?: string;
            /** @enum {string} */
            status: "sent" | "delivered" | "failed";
        };
        UpdateWebhookInputBody: {
            /** @description Re-enabling clears any automatic pause. */
            enabled?: boolean;
            events?: string[];
            name?: string;
            /** Format: uri */
            url?: string;
        };
        UsageView: {
            /** Format: int32 */
            received_this_month: number;
            /** Format: int32 */
            received_today: number;
            /** Format: int32 */
            sent_this_month: number;
            /** Format: int32 */
            sent_today: number;
        };
        User: {
            avatar_url: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            deletion_requested_at: string | null;
            email: string;
            /** Format: date-time */
            email_verified_at: string | null;
            id: string;
            /** Format: date-time */
            last_login_at: string | null;
            name: string | null;
            onboarding: unknown;
            role: string;
            /** Format: date-time */
            updated_at: string;
        };
        UserOutputBody: {
            user: components["schemas"]["User"];
        };
        VerifyEmailInputBody: {
            /** @description The 6-digit code from the email. */
            code: string;
        };
        Webhook: {
            /** Format: date-time */
            created_at: string;
            disabled_reason: string | null;
            enabled: boolean;
            events: string[];
            /** Format: int64 */
            failure_count: number;
            id: string;
            /** Format: date-time */
            last_attempt_at: string | null;
            /** Format: date-time */
            last_failure_at: string | null;
            /** Format: date-time */
            last_success_at: string | null;
            name: string | null;
            /** Format: int64 */
            success_count: number;
            /** Format: date-time */
            updated_at: string;
            url: string;
        };
        WebhookCreatedOutputBody: {
            /** @description Signing secret, shown once. Verify X-Simhook-Signature with it. */
            secret: string;
            webhook: components["schemas"]["Webhook"];
        };
        WebhookOutputBody: {
            webhook: components["schemas"]["Webhook"];
        };
        WebhooksOutputBody: {
            data: components["schemas"]["Webhook"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "list-api-keys": {
        parameters: {
            query?: {
                /** @description Also return revoked keys. */
                include_revoked?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListKeysOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "create-api-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateKeyInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateKeyOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "delete-api-key": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description API key id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "rename-api-key": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameKeyInputBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "revoke-api-key": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description API key id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordInputBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetInputBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "request-password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetRequestInputBody"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "update-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "send-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "list-batches": {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchesOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "get-batch": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "device-self": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "device-unpair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "device-update-self": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevicePatchSelfBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "device-heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeartbeatInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "device-report-inbound": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InboundInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboundOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "device-messages": {
        parameters: {
            query?: {
                cursor?: string;
                direction?: "outbound" | "inbound";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagesOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "device-report-status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Message id from the outbox. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusReportInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "device-outbox": {
        parameters: {
            query?: {
                /** @description At most this many messages. Default 100. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutboxOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "pair-device": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "device-push-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushTokenInputBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "list-devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevicesOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "get-device": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device id from GET /v1/devices. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "unpair-device": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device id from GET /v1/devices. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "update-device": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevicePatchBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "set-default-device": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device id from GET /v1/devices. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "create-pairing-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairingCodeOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "get-pairing-code": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pairing code id from POST /v1/devices/pairing-codes. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairingStatusOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "list-messages": {
        parameters: {
            query?: {
                /** @description Only messages from one send. */
                batch_id?: string;
                /** @description next_cursor from a previous page. */
                cursor?: string;
                /** @description Comma-separated device ids. Default: all paired devices. */
                device_ids?: string;
                /** @description Filter by direction. */
                direction?: "outbound" | "inbound";
                /** @description Inclusive lower bound on created_at, RFC 3339. */
                from?: string;
                /** @description Page size, default 50. */
                limit?: number;
                /** @description desc (default) for newest first; asc to walk forward when polling. */
                order?: "desc" | "asc";
                /** @description Match against text, recipient, and sender. */
                q?: string;
                status?: "queued" | "dispatched" | "sent" | "delivered" | "failed" | "unknown" | "received";
                /** @description Exclusive upper bound on created_at, RFC 3339. */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagesOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "send-message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendInputBody"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "get-message": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "list-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlansOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "get-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stats"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "list-webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhooksOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "create-webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWebhookInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookCreatedOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "get-webhook": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "delete-webhook": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "update-webhook": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWebhookInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "rotate-webhook-secret": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "test-webhook": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "list-deliveries": {
        parameters: {
            query?: {
                cursor?: string;
                event?: "message.received" | "message.sent" | "message.delivered" | "message.failed" | "message.unknown" | "device.online" | "device.offline" | "ping";
                from?: string;
                limit?: number;
                status?: "pending" | "delivered" | "retrying" | "failed";
                to?: string;
                webhook_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveriesOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    "get-delivery": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
}
